export default Object.freeze({
    CONNECT: 'teevid/sdk/connect',
    CONNECTION_DISCONNECT:'connectioin_disconnect',
    CONNECTION_DISCONNECTED:'teevid/sdk/disconnected',
    LOGIN:'v2chat/teevid/login',
    LOGIN_SUCCESS_RESULT:'v2chat/loginSuccess/result',
    LOGIN_ERROR_RESULT:'v2chat/loginError/result',
    LOGOUT:'v2chat/teevid/logout',
    LOGOUT_SUCCESS:'v2chat/logout/success',
    // CONNECTION_ERROR_RESULT:'v2chat/teevid/connection/connect/error',
    // CONNECTION_SUCCESS_RESULT:'v2chat/teevid/connection/connect/success',
    // CONNECTION_DisConnect_RESULT:'v2chat/teevid/connection/disConnect/success',
    // STORYBOARD_CHANGE_SLIDENUMBER:'v2chat/teevid/storyBoard/change/slidNumber',
    // TV_MEETING_SLIDE_CHANGED:'teevid/meeting/slide_number_changed',
    // SET_OWNER_PIN:'v2chat/teevid/meeting/set_owner_pin',
    // OWNER_PIN_SUCCESS:'v2chat/teevid/participant/owner-pin-success',
    // OWNER_PIN_SUCCESS_RESULT:'v2chat/teevid/participant/owner-pin-success_result',
    // OWNER_PIN_ERROR_RESULT:'v2chat/teevid/participant/owner-pin-error_result',
  })